### PR TITLE
Fix bold in README.de_DE.md

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Review by avmentzer — APPROVED** [review]
Thanks 😃

**Review by avmentzer — COMMENTED** [review]
Line 40 should say:

 `Bitte lies den [Mitarbeit](#mitarbeit) Abschnitt unten.` 

so that the anchor tag works properly. (sry but not noticed before...)

**Comment by JakeRoggenbuck** [comment]
Yup, thanks!

**Comment by JakeRoggenbuck** [comment]
pulled from main, to avoid merge conflict with the slack code commit

**Pull request merged**
