### PR TITLE
Add Chinese Community information

### PR DESCRIPTION
**Pull request by oubayun**
Add Chinese Community information

### CODE REVIEW

**Comment by woshoxxx** [comment]
社区建立得好快啊！
The community builds so quickly!

**Comment by woshoxxx** [comment]
This translation isn't full,
Please read my PR(https://github.com/rocky-linux/rocky/pull/46)

**Comment by shenxianpeng** [comment]
Why read second-hand translation sites.

**Comment by oubayun** [comment]
> 该翻译不完整，
> 请阅读我的PR（[＃46](https://github.com/rocky-linux/rocky/pull/46)）

不好意思，我只是为了添加部份中文社区的信息，后续将逐步填充，您可以加我微信:rockylinuxcn 一起构建中文社区，或者我加您都可以。

**Comment by brianclemens** [comment]
We do not plan to support separate regional organizations right now. Closed in favour of #46.

**Pull request closed without merging**
