### PR TITLE
Proper Turkish Translation

### PR DESCRIPTION
**Pull request by Slevilex**
I've translated the readme properly, the previous was obviously machine translated. I tried to use the Turkish counterpart of words when I can, but I am not aware of any good translations of "upstream", "downstream" and "crowdsourcing".
I didn't build up from the previous translation. I translated it from the original English readme.
Thank you.

### CODE REVIEW

**Comment by Slevilex** [comment]
I forgot to mention, I didn't build up from the previous translation. I translated it from the original English readme.

**Comment by Slevilex** [comment]
@hbjydev Sorry for tagging, but could you take a lookü please?

**Comment by hbjydev** [comment]
Hi there @Slevilex -- I'm not the one who oversees this repo, so I'll hand off to @jorp @brianclemens or @gmkurtzer on this one :)

**Comment by brianclemens** [comment]
Hi @Slevilex
I am not currently merging pull requests to this repository. The majority of people watching this repository are interested in significant updates to the the Rocky Linux project itself, so I am not going to deluge them with updates until the next major milestone (when our release candidate is available). When Rocky Linux 8 is released this repository will simply direct visitors to our website and be archived.
Please direct translation efforts to our website and documentation rather than this repository.

**Comment by Slevilex** [comment]
@brianclemens @hbjydev Alright, thank you so much!
Have a nice day!

**Pull request closed without merging**
