### PR TITLE
docs: fix italian slang

### PR DESCRIPTION
**Pull request by Zaragon-AQ**
Hi guys,
I fixed some italian slang.

### CODE REVIEW

**Review by FrancescoDiMaggio — COMMENTED** [review]
Proper fix

**Comment by Zaragon-AQ** [comment]
@FrancescoDiMaggio thx

**Review by Zaragon-AQ — COMMENTED** [review]
update slack url

**Comment by hbjydev** [comment]
@Zaragon-AQ Can you resolve the conflicts? Someone'll merge after that :)

**Pull request closed without merging**
