### PR TITLE
Add Latin American Spanish translation of README.md

### PR DESCRIPTION
**Pull request by marcocen**
This PR adds a spanish translation of the readme. I specify Latin American spanish, but it could be added as a general spanish translation instead.

### CODE REVIEW

**Comment by hc6pe** [comment]
In my opinion there is no need to separate latinamerican Spanish from the peninsular Spanish. It should be simply Spanish as it is one and Spanish speaking people from both sides of the Atlantic understand each other.

**Comment by Addvilz** [comment]
Indeed. There is no point in duplicating.

**Review by magicdrums — APPROVED** [review]
Veo que esta bien la traduccion, la traduccion de español normal esta con temas de formato en traslate google

**Comment by marcocen** [comment]
I agree that there's no need to duplicate the spanish translation, I clarified that this one was written in a more latin-american dialect just in case.

This one can be used with no problem as a general spanish translation.

**Comment by Addvilz** [comment]
@magicdrums aquí, porfa use inglés, hay mantenedores que no lo entienden.

Because this pull request has more seniority, and it indeed feels more readable than #70 - let's rename the README file as general Spanish, and use this instead of #70.

**Comment by magicdrums** [comment]
> @magicdrums aquí, porfa hablamos inglés, hay mantenedores que no lo entienden.
> 
> Because this pull request has more seniority, and it indeed feels more readable than #70 - let's rename the README file as general Spanish, and use this instead of #70.

Ready Corrected! :-)

**Comment by DSJ2** [comment]
I agree.

**Pull request merged**
